# Generated by Django 2.0.2 on 2020-12-30 20:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('project', models.CharField(max_length=1024)),
                ('issue_type', models.CharField(max_length=1024)),
                ('summary', models.CharField(max_length=2048)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(max_length=16)),
                ('priority', models.CharField(max_length=16)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
