# Generated by Django 3.1.7 on 2021-10-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='issue_type',
            new_name='issueType',
        ),
    ]
