# Generated by Django 3.1.7 on 2021-10-29 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_auto_20211023_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketimage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketImages', to='jira.ticket'),
        ),
    ]
