# Generated by Django 2.0.2 on 2020-12-31 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jira', '0003_ticket_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
