# Generated by Django 2.0.2 on 2020-12-31 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0004_ticket_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
