# Generated by Django 2.0.2 on 2020-12-31 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0005_auto_20201231_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
