# Generated by Django 2.0.2 on 2020-12-31 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0006_auto_20201231_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticketimages/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.Ticket')),
            ],
        ),
    ]
