# Generated by Django 2.0.2 on 2021-01-05 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0010_auto_20210104_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sub_task',
            field=models.ManyToManyField(blank=True, related_name='sub_tasks', to='jira.Ticket'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 19, 20, 0, 18, 195359)),
        ),
    ]
