# Generated by Django 2.0.2 on 2021-01-06 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0011_auto_20210105_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 20, 13, 32, 9, 745692)),
        ),
    ]
