# Generated by Django 2.0.2 on 2021-01-06 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0012_auto_20210106_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 20, 13, 40, 34, 150828)),
        ),
    ]
