# Generated by Django 2.0.2 on 2021-01-06 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0013_auto_20210106_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 20, 14, 56, 26, 821373)),
        ),
    ]
