# Generated by Django 3.1.7 on 2021-04-02 11:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_title', models.TextField()),
                ('community_url', models.CharField(max_length=512)),
                ('community_description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('community_banner', models.ImageField(blank=True, null=True, upload_to='communitybanner/')),
                ('community_logo', models.ImageField(blank=True, default='communitylogo/defaultimg/default-community-logo.jpg', null=True, upload_to='communitylogo/')),
                ('community_dislikes', models.ManyToManyField(related_name='community_dislikes', to=settings.AUTH_USER_MODEL)),
                ('community_likes', models.ManyToManyField(related_name='community_likes', to=settings.AUTH_USER_MODEL)),
                ('community_members', models.ManyToManyField(related_name='community_members', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_title', models.TextField()),
                ('forum_url', models.CharField(max_length=512)),
                ('forum_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('anonymous', models.BooleanField(default=False)),
                ('forum_image', models.ImageField(blank=True, null=True, upload_to='forumimage/')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.community')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum_dislikes', models.ManyToManyField(related_name='forum_dislikes', to=settings.AUTH_USER_MODEL)),
                ('forum_likes', models.ManyToManyField(related_name='forum_likes', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, related_name='forum_watchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Forums',
            },
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('anonymous', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='forum.forum')),
                ('forum_comment_dislikes', models.ManyToManyField(related_name='forum_comment_dislikes', to=settings.AUTH_USER_MODEL)),
                ('forum_comment_likes', models.ManyToManyField(related_name='forum_comment_likes', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.forumcomment')),
            ],
            options={
                'verbose_name_plural': 'ForumComment',
            },
        ),
    ]
