# Generated by Django 3.1.7 on 2021-10-23 15:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.CharField(max_length=512)),
                ('tags', models.CharField(max_length=2048)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='community-banner/')),
                ('logo', models.ImageField(blank=True, default='community-logo/default-community-logo.jpg', null=True, upload_to='community-logo/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='communityDislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='communityLikes', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='communityMembers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('anonymous', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='forum-image/')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='forum.community')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='forumDislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='forumLikes', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, related_name='forumWatchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Forums',
            },
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('anonymous', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, null=True, related_name='forumCommentDislikes', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forumComments', to='forum.forum')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='forumCommentLikes', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.forumcomment')),
            ],
            options={
                'verbose_name_plural': 'ForumComment',
            },
        ),
    ]
