# Generated by Django 3.1.7 on 2021-07-21 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='communityDislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='communityLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='communityMembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='forumDislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='forumLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='watchers',
            field=models.ManyToManyField(blank=True, null=True, related_name='forumWatchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='forumCommentDislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='forumCommentLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
