# Generated by Django 3.1.7 on 2021-11-06 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='forumCommentDislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='forumCommentLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
