# Generated by Django 3.1.7 on 2022-01-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20211106_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Community'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name_plural': 'Forum'},
        ),
    ]
