# Generated by Django 3.1.7 on 2022-02-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutoring', '0015_auto_20220218_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalKey', models.CharField(max_length=1024)),
                ('reference', models.CharField(max_length=2048)),
                ('deleteFl', models.BooleanField(default=False)),
                ('orderNo', models.IntegerField(blank=True, default=1, null=True)),
                ('versionNo', models.IntegerField(blank=True, default=1, null=True)),
                ('frequency', models.ForeignKey(limit_choices_to={'componentGroup__code': 'TASK_FREQUENCY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutoring.component')),
            ],
        ),
    ]
