# Generated by Django 3.1.7 on 2022-01-14 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211231_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogin',
            options={'verbose_name_plural': 'UserLogin'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name_plural': 'UserSession'},
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='logoutTime',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
    ]
