# Generated by Django 3.1.7 on 2021-11-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211119_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='education',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='avatars/mouse.png', null=True, upload_to='profile-picture'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='avatars/kangaroo.png', null=True, upload_to='profile-picture'),
        ),
    ]
