# Generated by Django 3.1.7 on 2021-11-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211119_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='chargeRate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
