# Generated by Django 3.1.7 on 2021-12-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_getintouch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='getintouch',
            options={'verbose_name_plural': 'GetInTouch'},
        ),
    ]
