# Generated by Django 3.1.7 on 2022-01-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_auto_20220101_0843'),
        ('accounts', '0010_auto_20211231_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='tutorComponents', to='tutoring.Component'),
        ),
    ]
