# Generated by Django 3.1.7 on 2022-01-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0010_auto_20220101_1803'),
        ('accounts', '0011_tutorprofile_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='components',
            field=models.ManyToManyField(blank=True, limit_choices_to={'componentGroup__code': 'TUTOR_FEATURE'}, related_name='tutorComponents', to='tutoring.Component'),
        ),
    ]
