# Generated by Django 3.1.7 on 2022-01-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0011_auto_20220102_1946'),
        ('accounts', '0012_auto_20220101_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='features',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='teachingLevels',
            field=models.ManyToManyField(blank=True, limit_choices_to={'componentGroup__code': 'EDUCATION_LEVEL'}, related_name='teachingComponent', to='tutoring.Component'),
        ),
    ]
