# Generated by Django 3.1.7 on 2022-01-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0011_auto_20220102_1946'),
        ('accounts', '0013_auto_20220102_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='components',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='features',
            field=models.ManyToManyField(blank=True, limit_choices_to={'componentGroup__code': 'TUTOR_FEATURE'}, related_name='featuresComponents', to='tutoring.Component'),
        ),
    ]
