# Generated by Django 3.1.7 on 2022-01-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0012_auto_20220103_1137'),
        ('accounts', '0014_auto_20220102_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='features',
            field=models.ManyToManyField(blank=True, limit_choices_to={'componentGroup__code': 'TUTOR_FEATURE'}, null=True, related_name='featuresComponents', to='tutoring.Component'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='teachingLevels',
            field=models.ManyToManyField(blank=True, limit_choices_to={'componentGroup__code': 'EDUCATION_LEVEL'}, null=True, related_name='teachingComponent', to='tutoring.Component'),
        ),
    ]
