# Generated by Django 3.1.7 on 2022-01-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220103_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'ordering': ['-id'], 'verbose_name_plural': 'TutorProfiles'},
        ),
    ]
