# Generated by Django 3.1.7 on 2022-01-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220110_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name_plural': 'StudentProfile'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('name',), 'verbose_name_plural': 'Subject'},
        ),
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'ordering': ['-id'], 'verbose_name_plural': 'TutorProfile'},
        ),
    ]
