# Generated by Django 3.1.7 on 2022-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0013_auto_20220114_1927'),
        ('accounts', '0017_auto_20220114_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='features',
            field=models.ManyToManyField(blank=True, limit_choices_to={'componentGroup__code': 'TUTOR_FEATURE'}, related_name='featuresComponents', to='tutoring.Component'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='teachingLevels',
            field=models.ManyToManyField(blank=True, limit_choices_to={'componentGroup__code': 'EDUCATION_LEVEL'}, related_name='teachingComponent', to='tutoring.Component'),
        ),
    ]
