# Generated by Django 3.1.7 on 2022-02-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220205_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='secondaryKey',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='secondaryKey',
            new_name='url',
        ),
        migrations.AddIndex(
            model_name='countries',
            index=models.Index(fields=['name'], name='accounts_co_name_2fa6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['url'], name='accounts_st_url_ed9353_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorprofile',
            index=models.Index(fields=['url'], name='accounts_tu_url_ccc73e_idx'),
        ),
    ]
