# Generated by Django 3.1.7 on 2022-03-04 17:31

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0019_auto_20220212_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentsParent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(default=accounts.models.getParentCode, max_length=8)),
                ('profilePicture', models.ImageField(blank=True, default=accounts.models.getRandomImageForAvatar, null=True, upload_to='profile-picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parentProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ParentProfile',
            },
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['url'], name='accounts_pa_url_a1f79c_idx'),
        ),
    ]
