# Generated by Django 3.1.7 on 2021-10-23 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='questionAnswerDislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='questionAnswerLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionanswercomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='questionAnswerCommentDislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionanswercomment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='questionAnswerCommentLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
