# Generated by Django 3.1.7 on 2021-11-06 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring', '0002_auto_20211023_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sundayMorning', models.BooleanField(default=False)),
                ('sundayAfternoon', models.BooleanField(default=False)),
                ('sundayEvening', models.BooleanField(default=False)),
                ('mondayMorning', models.BooleanField(default=False)),
                ('mondayAfternoon', models.BooleanField(default=False)),
                ('mondayEvening', models.BooleanField(default=False)),
                ('tuesdayMorning', models.BooleanField(default=False)),
                ('tuesdayAfternoon', models.BooleanField(default=False)),
                ('tuesdayEvening', models.BooleanField(default=False)),
                ('wednesdayMorning', models.BooleanField(default=False)),
                ('wednesdayAfternoon', models.BooleanField(default=False)),
                ('wednesdayEvening', models.BooleanField(default=False)),
                ('thursdayMorning', models.BooleanField(default=False)),
                ('thursdayAfternoon', models.BooleanField(default=False)),
                ('thursdayEvening', models.BooleanField(default=False)),
                ('fridayMorning', models.BooleanField(default=False)),
                ('fridayAfternoon', models.BooleanField(default=False)),
                ('fridayEvening', models.BooleanField(default=False)),
                ('saturdayMorning', models.BooleanField(default=False)),
                ('saturdayAfternoon', models.BooleanField(default=False)),
                ('saturdayEvening', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='questionAnswerDislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='questionAnswerLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionanswercomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='questionAnswerCommentDislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionanswercomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='questionAnswerCommentLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorreview',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='tutorReviewDislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tutorReviewLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
