# Generated by Django 3.1.7 on 2021-11-21 19:08

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tutorprofile_chargerate'),
        ('tutoring', '0005_auto_20211119_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=1024)),
                ('colour', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoursTaught', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('points', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentLessons', to='accounts.studentprofile')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorLessons', to='accounts.tutorprofile')),
            ],
        ),
    ]
