# Generated by Django 3.1.7 on 2021-11-26 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring', '0006_feature_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=1024)),
                ('icon', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentLesson', to='tutoring.lesson')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentPayee', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentPayer', to=settings.AUTH_USER_MODEL)),
                ('paymentMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentMethod', to='tutoring.paymentmethod')),
            ],
        ),
    ]
