# Generated by Django 3.1.7 on 2022-01-01 08:00

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_payment_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalKey', models.CharField(blank=True, max_length=2048, null=True)),
                ('reference', models.CharField(blank=True, max_length=2048, null=True)),
                ('languageKey', models.CharField(blank=True, max_length=2048, null=True)),
                ('code', models.CharField(blank=True, max_length=2048, null=True)),
                ('icon', models.CharField(blank=True, max_length=2048, null=True)),
                ('deleteFl', models.BooleanField(default=False)),
                ('colour', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('versionNo', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalKey', models.CharField(blank=True, max_length=2048, null=True)),
                ('reference', models.CharField(blank=True, max_length=2048, null=True)),
                ('languageKey', models.CharField(blank=True, max_length=2048, null=True)),
                ('code', models.CharField(blank=True, max_length=2048, null=True)),
                ('icon', models.CharField(blank=True, max_length=2048, null=True)),
                ('deleteFl', models.BooleanField(default=False)),
                ('colour', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('versionNo', models.IntegerField(blank=True, default=1, null=True)),
                ('componentGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentGroup', to='tutoring.componentgroup')),
            ],
        ),
    ]
