# Generated by Django 3.1.7 on 2022-01-01 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_component_componentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='orderNo',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='componentgroup',
            name='orderNo',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='componentGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='tutoring.componentgroup'),
        ),
    ]
