# Generated by Django 3.1.7 on 2022-01-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_auto_20220101_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paymentMethod',
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentComponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentComponent', to='tutoring.component'),
        ),
    ]
