# Generated by Django 3.1.7 on 2022-01-02 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0010_auto_20220101_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['componentGroup', 'orderNo']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentComponent',
            field=models.ForeignKey(limit_choices_to={'componentGroup__code': 'PAYMENT_METHOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentComponent', to='tutoring.component'),
        ),
    ]
