# Generated by Django 3.1.7 on 2022-01-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0011_auto_20220102_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['componentGroup', 'orderNo'], 'verbose_name_plural': 'Component'},
        ),
        migrations.AlterModelOptions(
            name='componentgroup',
            options={'verbose_name_plural': 'ComponentGroup'},
        ),
    ]
