# Generated by Django 3.1.7 on 2022-01-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0012_auto_20220103_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availability'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name_plural': 'Feature'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': 'Lesson'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payment'},
        ),
        migrations.AlterModelOptions(
            name='questionanswercomment',
            options={'verbose_name_plural': 'QuestionAnswerComment'},
        ),
    ]
