# Generated by Django 3.1.7 on 2022-02-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0013_auto_20220114_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentgroup',
            name='internalKey',
            field=models.CharField(blank=True, max_length=2048, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('componentGroup', 'internalKey')},
        ),
    ]
