# Generated by Django 3.1.7 on 2022-02-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0014_auto_20220212_1803'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='component',
            unique_together=set(),
        ),
    ]
